---
# =============================================================================
# Handlers: mongodb role
# =============================================================================

- name: restart mongod
  service:
    name: mongod
    state: restarted
