# MongoDB runs on EC2 (10.0.155.19) - this Service + Endpoints
# allows K8s pods to reach it via dns name "mongo" as before
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: osm
spec:
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

---
apiVersion: v1
kind: Endpoints
metadata:
  name: mongo
  namespace: osm
subsets:
  - addresses:
      - ip: "10.0.155.19"
    ports:
      - port: 27017
